version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:6.1.3
    ports:
      - "9125:9125/udp"

  kivana:
    image: docker.elastic.co/kibana/kibana:6.1.3
    ports:
      - "5601:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    ports:
      - "9200:9200"
